---
- hosts: leafs
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - interfaces
    - quagga

- hosts: spines
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - interfaces
    - quagga